version: '3.9'

services:

  db-service:
    image: postgres:17
    container_name: db-service
    restart: unless-stopped
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sasa1234
      POSTGRES_DB: system_monitor
    networks:
      - system-network

networks:
  system-network:
    driver: bridge
